version: '3.7'

services:
  api:
    build:
        context: ./tolstoi-api
        dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - DISPLAY=host.docker.internal:0
    command: /bin/bash -c "python3 app.py && celery -A my_celery.celery_tasks.celery_app worker --loglevel=info"
    ports:
        - "5000:5000"
    container_name: tolstoi-api
    volumes:
      - ./tolstoi-api/:/app
    networks:
      - tolstoi-network
    tty: true

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: tolstoi-redis
    networks:
        - tolstoi-network

networks:
    tolstoi-network:
        name: tolstoi-network
        driver: bridge